apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello2-tchl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello2-tchl
    app.kubernetes.io/part-of: "n"
  name: node-express-hello2-tchl
  namespace: burrzinga-hac-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: node-express-hello2-tchl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: node-express-hello2-tchl
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/burrzinga-hac-tenant/n/node-express-hello2-tchl@sha256:95ac145e93cbe7eaa42fd09521cb2f332771638db30b28c3607d1e3ad33b4d15
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
