apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello2-tchl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello2-tchl
    app.kubernetes.io/part-of: "n"
  name: node-express-hello2-tchl
  namespace: burrzinga-hac-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: node-express-hello2-tchl
    weight: null
status: {}
